# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set a working directory
WORKDIR /app

# Copy all files to the container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir mcp[cli] httpx pydantic python-dotenv

# Set environment variables
ENV CACHE_TTL_SECONDS=600
ENV RATE_LIMIT_INTERVAL=1.0

# Command to run the MCP server
CMD ["python", "server.py"]